package scripting

import (
	"sync"
	"testing"
	"time"
)

type Address struct {
	City    string
	Country string
	Zip     int
}

type Order struct {
	ID     string
	Amount float64
	Paid   bool
}

type Profile struct {
	Email   string
	Phone   string
	Address Address
}

type ComplexUser struct {
	Name    string
	Age     int
	Active  bool
	Tags    []string
	Scores  []int
	Profile Profile
	Orders  []Order
	Meta    map[string]interface{}
}

func TestExecute_ComplexMutation(t *testing.T) {
	svc := NewScriptCommonService()

	u := &ComplexUser{
		Name:   "Juan",
		Age:    30,
		Active: false,
		Tags:   []string{"user", "basic"},
		Scores: []int{10, 20},
		Profile: Profile{
			Email: "juan@example.com",
			Phone: "12345",
			Address: Address{
				City:    "Madrid",
				Country: "Spain",
				Zip:     28001,
			},
		},
		Orders: []Order{
			{ID: "A1", Amount: 50, Paid: false},
			{ID: "B2", Amount: 100, Paid: true},
		},
		Meta: map[string]any{
			"role": "guest",
			"lvl":  1,
		},
	}

	script := `
		ctx.Age = ctx.Age + 10
		ctx.Active = true
		ctx.Tags.push("premium")
		ctx.Scores.push(30)
		ctx.Profile.Email = "updated@example.com"
		ctx.Profile.Address.City = "Barcelona"
		ctx.Profile.Address.Zip = 8000
		ctx.Orders[0].Paid = true
		ctx.Orders[1].Amount = ctx.Orders[1].Amount * 2
		ctx.Meta.role = "admin"
		ctx.Meta.extra = { note: "generated by script", ok: true }
		ctx.Meta.lvl = ctx.Meta.lvl + 4
	`

	err := svc.Execute(u, script)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if u.Age != 40 {
		t.Fatalf("Age expected 40, got %d", u.Age)
	}

	if u.Active != true {
		t.Fatalf("Active expected true, got %v", u.Active)
	}

	if len(u.Tags) != 3 || u.Tags[2] != "premium" {
		t.Fatalf("Tags incorrect: %v", u.Tags)
	}

	if len(u.Scores) != 3 || u.Scores[2] != 30 {
		t.Fatalf("Scores incorrect: %v", u.Scores)
	}

	if u.Profile.Email != "updated@example.com" {
		t.Fatalf("Profile.Email incorrect: %s", u.Profile.Email)
	}

	if u.Profile.Address.City != "Barcelona" {
		t.Fatalf("Address.City incorrect: %s", u.Profile.Address.City)
	}

	if u.Profile.Address.Zip != 8000 {
		t.Fatalf("Address.Zip incorrect: %d", u.Profile.Address.Zip)
	}

	if u.Orders[0].Paid != true {
		t.Fatalf("Order A1 should be paid")
	}

	if u.Orders[1].Amount != 200 {
		t.Fatalf("Order B2 Amount incorrect: %f", u.Orders[1].Amount)
	}

	if u.Meta["role"] != "admin" {
		t.Fatalf("Meta.role incorrect: %v", u.Meta["role"])
	}

	if u.Meta["lvl"].(float64) != 5 {
		t.Fatalf("Meta.lvl incorrect: %v", u.Meta["lvl"])
	}

	extra := u.Meta["extra"].(map[string]interface{})
	if extra["note"] != "generated by script" {
		t.Fatalf("extra.note incorrect: %v", extra["note"])
	}

	if extra["ok"] != true {
		t.Fatalf("extra.ok incorrect: %v", extra["ok"])
	}
}

type TimeDTO struct {
	Start   time.Time
	End     time.Time
	Diff    int
	Next    time.Time
	Payload map[string]time.Time
}

func TestExecute_TimeOperationsWithTimeTime(t *testing.T) {
	svc := NewScriptCommonService()

	start := time.Date(2024, 1, 5, 10, 30, 0, 0, time.UTC)
	end := time.Date(2024, 1, 12, 10, 30, 0, 0, time.UTC)

	dto := &TimeDTO{
		Start:   start,
		End:     end,
		Diff:    0,
		Next:    time.Time{},
		Payload: map[string]time.Time{"created": start},
	}

	script := `
		let s = new Date(ctx.Start)
		let e = new Date(ctx.End)

		let diffMs = e - s
		let diffDays = diffMs / (1000 * 60 * 60 * 24)
		ctx.Diff = diffDays

		let nextObj = new Date(s)
		nextObj.setDate(nextObj.getDate() + 45)
		ctx.Next = nextObj.toISOString()

		let c = new Date(ctx.Payload.created)
		c.setHours(c.getHours() + 5)
		ctx.Payload.created = c.toISOString()
	`

	err := svc.Execute(dto, script)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if dto.Diff != 7 {
		t.Fatalf("expected Diff=7 got %d", dto.Diff)
	}

	expectedNext := start.AddDate(0, 0, 45)
	if !dto.Next.Equal(expectedNext) {
		t.Fatalf("expected Next=%s got %s", expectedNext, dto.Next)
	}

	created := dto.Payload["created"]
	expectedCreated := start.Add(5 * time.Hour)

	if !created.Equal(expectedCreated) {
		t.Fatalf("expected Payload.created %s got %s", expectedCreated, created)
	}
}

type SimpleUser struct {
	Name string
	Age  int
}

func TestExecute_InvalidTypeError(t *testing.T) {
	svc := NewScriptCommonService()

	u := &SimpleUser{
		Name: "Test",
		Age:  10,
	}

	script := `
		ctx.Age = "invalid"
	`

	err := svc.Execute(u, script)
	if err == nil {
		t.Fatalf("expected error, got nil")
	}

	if u.Age != 10 {
		t.Fatalf("expected Age=10, got %d", u.Age)
	}
}

func TestExecute_ScriptSyntaxError(t *testing.T) {
	svc := NewScriptCommonService()

	u := &SimpleUser{
		Name: "Test",
		Age:  10,
	}

	script := `
		ctx.Age =
	`

	err := svc.Execute(u, script)
	if err == nil {
		t.Fatalf("expected script error, got nil")
	}

	if u.Age != 10 {
		t.Fatalf("expected Age=10, got %d", u.Age)
	}
}

func TestExecute_Concurrent(t *testing.T) {
	svc := NewScriptCommonService()

	var wg sync.WaitGroup
	n := 20

	for i := 0; i < n; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			u := &SimpleUser{
				Name: "User",
				Age:  i,
			}
			script := `
				ctx.Age = ctx.Age + 1
				ctx.Name = ctx.Name + "_x"
			`
			err := svc.Execute(u, script)
			if err != nil {
				t.Errorf("unexpected error in goroutine %d: %v", i, err)
				return
			}
			if u.Age != i+1 {
				t.Errorf("goroutine %d: expected Age=%d got %d", i, i+1, u.Age)
			}
			if u.Name != "User_x" {
				t.Errorf("goroutine %d: expected Name=User_x got %s", i, u.Name)
			}
		}(i)
	}

	wg.Wait()
}

type TaggedProfile struct {
	Email string `json:"email"`
	Phone string `json:"phone"`
}

type TaggedUser struct {
	FullName string        `json:"full_name"`
	Age      int           `json:"age"`
	Active   bool          `json:"active"`
	Tags     []string      `json:"tags"`
	Profile  TaggedProfile `json:"profile"`
}

func TestExecute_WithJSONTags(t *testing.T) {
	svc := NewScriptCommonService()

	u := &TaggedUser{
		FullName: "John Doe",
		Age:      20,
		Active:   false,
		Tags:     []string{"user"},
		Profile: TaggedProfile{
			Email: "john@example.com",
			Phone: "12345",
		},
	}

	script := `
		ctx.full_name = "Jane Doe"
		ctx.age = ctx.age + 2
		ctx.active = true
		ctx.tags.push("vip")
		ctx.profile.email = "jane@example.com"
		ctx.profile.phone = "99999"
	`

	err := svc.Execute(u, script)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if u.FullName != "Jane Doe" {
		t.Fatalf("FullName expected Jane Doe, got %s", u.FullName)
	}

	if u.Age != 22 {
		t.Fatalf("Age expected 22, got %d", u.Age)
	}

	if !u.Active {
		t.Fatalf("Active expected true, got %v", u.Active)
	}

	if len(u.Tags) != 2 || u.Tags[1] != "vip" {
		t.Fatalf("Tags incorrect: %v", u.Tags)
	}

	if u.Profile.Email != "jane@example.com" {
		t.Fatalf("Email expected jane@example.com, got %s", u.Profile.Email)
	}

	if u.Profile.Phone != "99999" {
		t.Fatalf("Phone expected 99999, got %s", u.Profile.Phone)
	}
}

func TestExecute_EmptyScript(t *testing.T) {
	svc := NewScriptCommonService()

	u := &SimpleUser{
		Name: "John",
		Age:  30,
	}

	err := svc.Execute(u, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if u.Name != "John" {
		t.Fatalf("expected Name=John got %s", u.Name)
	}

	if u.Age != 30 {
		t.Fatalf("expected Age=30 got %d", u.Age)
	}
}
